[package]
name = "Terralistic"
version = "0.1.0"
edition = "2021"
description = "test"

[[bin]]
name = "Terralistic"
path = "Client/main.rs"

[[bin]]
name = "TerralisticServer"
path = "Server/main.rs"

[dependencies]
graphics = {"path" = "Libraries/graphics/"}
events = {"path" = "Libraries/events/"}
shared_mut = {"path" = "Libraries/shared_mut/"}
resource_path = {"path" = "Shared/resource_path/"}
blocks = {"path" = "Shared/blocks/"}

[package.metadata.bundle.bin.Terralistic]
name = "Terralistic"
identifier = "com.Zorz42.Terralistic"
icon = ["Build/Resources/icon.icns"]
version = "1.0.0"
copyright = "Copyright (c) Zorz42 2022. All rights reserved."
category = "Game"
short_description = "Terralistic is a game."
long_description = """
Terralistic is a Terraria fan game.
It has some technical stuff that I miss in Terraria,
like: native mod support, good performance,
custom programming language for mods, online accounts,
good ui and so on...
"""
deb_depends = []
osx_frameworks = []

[package.metadata.bundle.bin.TerralisticServer]
name = "TerralisticServer"
identifier = "com.Zorz42.TerralisticServer"
icon = ["Build/Resources/icon.icns"]
version = "1.0.0"
copyright = "Copyright (c) Zorz42 2022. All rights reserved."
category = "Game"
short_description = "Terralistic is a game."
long_description = """
Terralistic is a Terraria fan game.
It has some technical stuff that I miss in Terraria,
like: native mod support, good performance,
custom programming language for mods, online accounts,
good ui and so on...
"""
deb_depends = []
osx_frameworks = []