[package]
name = "Terralistic-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "Client"
path = "Client/main.rs"

[[bin]]
name = "Server"
path = "Server/main.rs"