[package]
name = "Terralistic"
version = "0.1.0"
edition = "2021"
description = "test"
build = "BuildProject/build.rs"

[[bin]]
name = "Terralistic"
path = "Client/main.rs"

[[bin]]
name = "TerralisticServer"
path = "Server/main.rs"

[dependencies]
graphics = {"path" = "Libraries/graphics/"}
events = {"path" = "Libraries/events/"}
shared_mut = {"path" = "Libraries/shared_mut/"}
shared = {"path" = "Shared/"}
terralistic_server = {"path" = "Server/server_impl/"}
rand = "0.8.4"
directories = "4.0.1"
chrono = "0.4.19"
queues = "1.0.2"

[build-dependencies]
png = "0.17.7"
snap = "1.0.5"
graphics = {"path" = "Libraries/graphics/"}

[package.metadata.bundle.bin.Terralistic]
name = "Terralistic"
identifier = "com.Zorz42.Terralistic"
icon = ["Build/Resources/icon.icns"]
version = "1.0.0"
copyright = "Copyright (c) Zorz42 2022. All rights reserved."
category = "Game"
short_description = "Terralistic is a game."
long_description = """
Terralistic is a Terraria fan game.
It has some technical stuff that I miss in Terraria,
like: native mod support, good performance,
custom programming language for mods, online accounts,
good ui and so on...
"""
deb_depends = []
osx_frameworks = []

[package.metadata.bundle.bin.TerralisticServer]
name = "TerralisticServer"
identifier = "com.Zorz42.TerralisticServer"
icon = ["Build/Resources/icon.icns"]
version = "1.0.0"
copyright = "Copyright (c) Zorz42 2022. All rights reserved."
category = "Game"
short_description = "Terralistic is a game."
long_description = """
Terralistic is a Terraria fan game.
It has some technical stuff that I miss in Terraria,
like: native mod support, good performance,
custom programming language for mods, online accounts,
good ui and so on...
"""
deb_depends = []
osx_frameworks = []