[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
gl = "0.14.0"
sdl2 = { version = "=0.35.1", features = ["bundled", "static-link"] }
sdl2-sys = "=0.35.1"
snap = "1.0.5"
bincode = "1.3.3"
serde = "1.0.130"
serde_derive = "1.0.130"
queues = "1.0.2"

[lib]
name = "graphics"
path = "graphics.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3