[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
gl = "0.14.0"
glfw = "0.46.0"
snap = "1.0.5"
bincode = "1.3.3"
serde = "1.0.130"
serde_derive = "1.0.130"

[lib]
name = "graphics"
path = "graphics.rs"
