[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
gl = "0.14.0"
snap = "1.0.5"
bincode = "1.3.3"
serde = "1.0.130"
serde_derive = "1.0.130"
queues = "1.0.2"
sdl2 = { version = "=0.35", features = ["bundled", "static-link"] }
sdl2-sys = "=0.35"
copypasta = "0.8.1"

# select sdl2 as sdl2-sys 0.35.1 for macos as it wont compile with 0.35.2
# for linux and windows use 0.35.2 as it wont compile with 0.35.1
[target.'cfg(target_os = "macos")'.dependencies]
sdl2-sys = "=0.35.1"


[lib]
name = "graphics"
path = "graphics.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3
