#pragma once

#define WHITE gfx::Color({230, 230, 230})
#define LIGHT_GREY gfx::Color({200, 200, 200})
#define GREY gfx::Color({85, 85, 85})
#define DARK_GREY gfx::Color({50, 50, 50})
#define BORDER_COLOR gfx::Color({100, 100, 100})
#define BLACK gfx::Color({0, 0, 0})
#define TRANSPARENT gfx::Color({0, 0, 0, 0})
#define SPACING 20
#define BUTTON_MARGIN 7
#define TRANSPARENCY 140
#define BLUR 200
#define SHADOW_INTENSITY 200
#define TEXT_INPUT_WIDTH 200

#define GFX_DEFAULT_BUTTON_COLOR TRANSPARENT
#define GFX_DEFAULT_BUTTON_BORDER_COLOR TRANSPARENT
#define GFX_DEFAULT_HOVERED_BUTTON_COLOR GREY
#define GFX_DEFAULT_HOVERED_BUTTON_BORDER_COLOR BORDER_COLOR
#define GFX_DEFAULT_TEXT_COLOR WHITE
#define GFX_SHADOW_BLUR BLUR
#define GFX_DEFAULT_BUTTON_MARGIN BUTTON_MARGIN
#define GFX_DEFAULT_TEXT_BOX_SHADOW_INTENSITY SHADOW_INTENSITY
#define GFX_DEFAULT_TEXT_INPUT_WIDTH TEXT_INPUT_WIDTH
