#ifndef theme_hpp
#define theme_hpp

#define WHITE gfx::Color({230, 230, 230})
#define LIGHT_GREY gfx::Color({200, 200, 200})
#define GREY gfx::Color({100, 100, 100})
#define BORDER_COLOR gfx::Color({100, 100, 100})
#define BLACK gfx::Color({0, 0, 0})
#define TRANSPARENT gfx::Color({0, 0, 0, 0})
#define SPACING 20
#define TRANSPARENCY 170
#define BLUR 4
#define SHADOW_INTENSITY 220
#define SHADOW_BLUR 4.4f

#define GFX_DEFAULT_BUTTON_COLOR TRANSPARENT
#define GFX_DEFAULT_HOVERED_BUTTON_COLOR GREY
#define GFX_DEFAULT_TEXT_COLOR WHITE
#define GFX_BACKGROUND_COLOR BLACK
#define GFX_DEFAULT_SHADOW_BLUR SHADOW_BLUR
#define GFX_DEFAULT_TEXT_BOX_SHADOW_INTENSITY SHADOW_INTENSITY
#define GFX_DEFAULT_BUTTON_MARGIN SPACING / 2

#endif
