[package]
name = "deprecated_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_mut = {"path" = "../shared_mut"}

[lib]
name = "deprecated_events"
path = "events.rs"
