[package]
name = "terralistic_server"
version = "0.1.0"
edition = "2021"
build = "../../BuildProject/build_server.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_mut = {"path" = "../../Libraries/shared_mut"}
events = {"path" = "../../Libraries/events"}
shared = {"path" = "../../Shared"}
bincode = "1.3.3"
rlua = "0.19.0"
rand = "0.8.4"
enet = "0.3.0"

[build-dependencies]
png = "0.17.7"
snap = "1.0.5"
graphics = {"path" = "../../Libraries/graphics/"}
shared = {"path" = "../../Shared/"}
darklua = "0.8.0"

[lib]
name = "terralistic_server"
path = "server.rs"