[package]
name = "terralistic_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_mut = {"path" = "../../Libraries/shared_mut"}
events = {"path" = "../../Libraries/events"}
shared = {"path" = "../../Shared"}
bincode = "1.3.3"
rlua = "0.19.0"
rand = "0.8.4"
enet = "0.3.0"
noise = "0.8.2"

[lib]
name = "terralistic_server"
path = "server.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3