[package]
name = "terralistic_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_mut = {"path" = "../../Libraries/shared_mut"}

[lib]
name = "terralistic_server"
path = "server.rs"