[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
events = {"path" = "../Libraries/events/"}
serde = "1.0.130"
serde_derive = "1.0.130"

[lib]
name = "shared"
path = "shared.rs"